const EventLocalizerData = {
    en: {
        Actions: "Actions",
        AddEvent: "Add event",
        BuyTicket:"Buy a ticket",
        Change: "Change",
        Delete:"Delete",
        Description: "Description",
        EventMessage: "On this page you can see all events",
        Events:	"Events",
        Name: "Name",
        ShowPeriod:	"Show period",
        ShowTime: "Show time",
        ShowTimeMinutes: "Show time minutes",
        ShowTimeHours: "Show time hours",
        TicketInformation: "Ticket information",
        VenueLayout: "Venue",
        DateEnd: "Show end date",
        DateStart: "Show start date",
        Layout:	"Layout",
        Save: "Save",
        URL: "Image URL",
        Price: "Price",
        DelMes: "Are you sure?",
        Failed: "Failed",
    },
    ru: {
        Actions: "Действия",
        AddEvent: "Добавить событие",
        BuyTicket: "Купить билет",
        Change: "Изменить",
        Delete:	"Удалить",
        Description: "Описание",
        EventMessage: "На этой странице вы можете увидеть все события",
        Events: "События",
        Name: "Название",
        ShowPeriod:	"Период показа",
        ShowTime: "Время показа",
        ShowTimeHours: "Время показа (часы)",
        ShowTimeMinutes: "Время показа (минуты)",
        TicketInformation: "Информация о билетах",
        VenueLayout: "Место проведения",
        DateEnd: "Дата конца показа",
        DateStart: "Дата начала показа",
        Layout: "Зал",
        Save: "Сохранить",
        URL: "URL изображения",
        Price:"Стоимость",
        DelMes: "Вы уверены?",
        Failed: "Не удалось",
    },
    "be-BY" : {
        Actions: "Дзеянні",
        AddEvent: "Дадаць падзею",
        BuyTicket: "Купіць білет",
        Change:	"Змяніць",
        Delete:	"Выдаліць",
        Description: "Апісанне",
        EventMessage: "На гэтай старонцы вы можаце ўбачыць усе падзеі",
        Events: "Падзеі",
        Name: "Назва",
        ShowPeriod: "Перыяд паказу",
        ShowTimeHours: "Час паказу (гадзіны)",
        ShowTimeMinutes: "Перыяд паказу (хвіліны)",
        ShowTime: "Час паказу",
        TicketInformation: "Інфармацыя пра квіткі",
        VenueLayout: "Месца правядзення",
        DateEnd: "Дата канца паказу",
        DateStart: "Дата пачатку паказу",
        Layout:	"Зала",
        Save: "Захаваць",
        URL: "URL выявы",
        Price: "Кошт",
        DelMes: "Вы ўпэўнены?",
        Failed: "Не атрымалася",
    }

}

export default EventLocalizerData;