const UserAccountLocalizerData = {
    en: {
        Actions: "Actions",
        Balance: "Balance",
        ChangePassword: "Change password",
        EditProfile: "Edit profile",
        Events: "Events",
        Language: "Language",
        PersonalArea: "Personal area",
        PurchaseHistory: "Purchase history",
        TimeZone: "Timezone",
        TopUpBalance: "Top up balance",
        Year: "Year of birth",
        Email: "Email",
        Name: "Name",
        Patronymic: "Patronymic",
        Save: "Save",
        Surname: "Surname",
        NewPassword: "New password",
        OldPassword: "Old password",
        Failed: "Failed",
    },
    ru: {
        Actions: "Действия",
        Balance: "Баланс",
        ChangePassword: "Изменить пароль",
        EditProfile: "Редактировать профиль",
        Events: "События",
        Language: "Язык",
        PersonalArea: "Личный кабинет",
        PurchaseHistory: "История покупок",
        TimeZone: "Часовой пояс",
        TopUpBalance: "Пополнить баланс",
        Year: "Год рождения",
        Email: "Почта",
        Name: "Имя",
        Patronymic: "Отчество",
        Save: "Сохранить",
        Surname: "Фамилия",
        NewPassword: "Новый пароль",
        OldPassword: "Старый пароль",
        Failed: "Не удалось",
    },
    "be-BY" : {
        Actions: "Дзеянні",
        Balance: "Баланс",
        ChangePassword: "Змяніць пароль",
        EditProfile: "Рэдагаваць профіль",
        Events: "Падзеі",
        Language: "Мова",
        PersonalArea: "Асабісты кабінет",
        PurchaseHistory: "Гісторыя пакупак",
        TimeZone: "Гадзінны пояс",
        TopUpBalance: "Папоўніць баланс",
        Year: "Год нараджэння",
        Email: "Пошта",
        Name: "Імя",
        Patronymic:	"Імя па бацьку",
        Save: "Захаваць",
        Surname: "Прозвішча",
        NewPassword: "Новы пароль",
        OldPassword: "Стары пароль",
        Failed: "Не атрымалася",
    }

}

export default UserAccountLocalizerData;